title: Zain (Zhenyuan) Ruan
logo: https://media.licdn.com/dms/image/C5103AQF_C12McNaXIA/profile-displayphoto-shrink_200_200/0?e=1566432000&v=beta&t=BL9AmjjoMIlyQZyKatKfZjoDg6SpUumzner2UvzRkJ4
google_analytics:
theme: jekyll-theme-minimal
