title: Grant Wilkins
logo: http://grantwilkins.github.io/photo.jpg
description: "gfwilki [at] clemson [dot] edu <br> 2009 Canterbury Road, <br>Kingsport, TN 37660"
google_analytics:
theme: jekyll-theme-minimal
