title: Zain (Zhenyuan) Ruan
logo: https://media.licdn.com/dms/image/C5103AQF_C12McNaXIA/profile-displayphoto-shrink_200_200/0?e=1568246400&v=beta&t=_d5RtN8Dg2P48BhS22jcmBRWoUhdArlawI790RUHifs
description: "zainruan [at] csail [dot] mit [dot] edu<br><br> Office 32-G978B,<br> 32 Vassar Street, <br>Cambridge, MA 02139"
google_analytics:
theme: jekyll-theme-minimal
